# Generated by Django 2.2.1 on 2019-10-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp', models.FloatField(default=0)),
                ('description', models.TextField(blank=True, default='Не заполнено', max_length=1200)),
                ('place', models.TextField(blank=True, default='Не заполнено', max_length=1200)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='volonteer',
            name='card_id',
            field=models.CharField(default='AA1234', max_length=6),
        ),
        migrations.AlterField(
            model_name='volonteer',
            name='allergy',
            field=models.BooleanField(default=False),
        ),
    ]
