# Generated by Django 2.2.1 on 2019-10-21 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_shelter_coordinate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shelter',
            old_name='coordinate',
            new_name='coordinates',
        ),
    ]
