# Generated by Django 2.2.1 on 2019-10-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_auto_20191022_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='allergy',
            field=models.BooleanField(default=True),
        ),
    ]
