# Generated by Django 2.2.1 on 2019-10-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_task_allergy'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.TextField(blank=True, default='Не заполнено', max_length=100),
        ),
    ]
