# Generated by Django 2.2.1 on 2019-10-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'STATUS_DEFAULT'), (2, 'STATUS_REQUESTED'), (3, 'STATUS_APPROVED')], default=1),
        ),
    ]
