# Generated by Django 2.2.1 on 2019-10-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0008_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volonteer',
            name='allergy',
            field=models.IntegerField(default=1),
        ),
    ]
