# Generated by Django 2.2.1 on 2019-10-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0009_auto_20191022_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volonteer',
            name='allergy',
            field=models.BooleanField(default=False),
        ),
    ]
